# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data_node.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='data_node.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0f\x64\x61ta_node.proto\"\n\n\x08\x45mptyMsg\"#\n\x11TouchDataResponse\x12\x0e\n\x06offset\x18\x01 \x01(\x05\" \n\rRmDataRequest\x12\x0f\n\x07offsets\x18\x01 \x03(\x05\">\n\x10WriteDataRequest\x12\x10\n\x06offset\x18\x01 \x01(\x05H\x00\x12\x0e\n\x04\x64\x61ta\x18\x02 \x01(\x0cH\x00\x42\x08\n\x06upload\"!\n\x0fReadDataRequest\x12\x0e\n\x06offset\x18\x01 \x01(\x05\" \n\x10ReadDataResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x32\xab\x01\n\x08\x44\x61taNode\x12&\n\x05touch\x12\t.EmptyMsg\x1a\x12.TouchDataResponse\x12\x1f\n\x02rm\x12\x0e.RmDataRequest\x1a\t.EmptyMsg\x12\'\n\x05write\x12\x11.WriteDataRequest\x1a\t.EmptyMsg(\x01\x12-\n\x04read\x12\x10.ReadDataRequest\x1a\x11.ReadDataResponse0\x01\x62\x06proto3'
)




_EMPTYMSG = _descriptor.Descriptor(
  name='EmptyMsg',
  full_name='EmptyMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=29,
)


_TOUCHDATARESPONSE = _descriptor.Descriptor(
  name='TouchDataResponse',
  full_name='TouchDataResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='offset', full_name='TouchDataResponse.offset', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=66,
)


_RMDATAREQUEST = _descriptor.Descriptor(
  name='RmDataRequest',
  full_name='RmDataRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='offsets', full_name='RmDataRequest.offsets', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=100,
)


_WRITEDATAREQUEST = _descriptor.Descriptor(
  name='WriteDataRequest',
  full_name='WriteDataRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='offset', full_name='WriteDataRequest.offset', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='WriteDataRequest.data', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='upload', full_name='WriteDataRequest.upload',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=102,
  serialized_end=164,
)


_READDATAREQUEST = _descriptor.Descriptor(
  name='ReadDataRequest',
  full_name='ReadDataRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='offset', full_name='ReadDataRequest.offset', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=166,
  serialized_end=199,
)


_READDATARESPONSE = _descriptor.Descriptor(
  name='ReadDataResponse',
  full_name='ReadDataResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='ReadDataResponse.data', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=201,
  serialized_end=233,
)

_WRITEDATAREQUEST.oneofs_by_name['upload'].fields.append(
  _WRITEDATAREQUEST.fields_by_name['offset'])
_WRITEDATAREQUEST.fields_by_name['offset'].containing_oneof = _WRITEDATAREQUEST.oneofs_by_name['upload']
_WRITEDATAREQUEST.oneofs_by_name['upload'].fields.append(
  _WRITEDATAREQUEST.fields_by_name['data'])
_WRITEDATAREQUEST.fields_by_name['data'].containing_oneof = _WRITEDATAREQUEST.oneofs_by_name['upload']
DESCRIPTOR.message_types_by_name['EmptyMsg'] = _EMPTYMSG
DESCRIPTOR.message_types_by_name['TouchDataResponse'] = _TOUCHDATARESPONSE
DESCRIPTOR.message_types_by_name['RmDataRequest'] = _RMDATAREQUEST
DESCRIPTOR.message_types_by_name['WriteDataRequest'] = _WRITEDATAREQUEST
DESCRIPTOR.message_types_by_name['ReadDataRequest'] = _READDATAREQUEST
DESCRIPTOR.message_types_by_name['ReadDataResponse'] = _READDATARESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EmptyMsg = _reflection.GeneratedProtocolMessageType('EmptyMsg', (_message.Message,), {
  'DESCRIPTOR' : _EMPTYMSG,
  '__module__' : 'data_node_pb2'
  # @@protoc_insertion_point(class_scope:EmptyMsg)
  })
_sym_db.RegisterMessage(EmptyMsg)

TouchDataResponse = _reflection.GeneratedProtocolMessageType('TouchDataResponse', (_message.Message,), {
  'DESCRIPTOR' : _TOUCHDATARESPONSE,
  '__module__' : 'data_node_pb2'
  # @@protoc_insertion_point(class_scope:TouchDataResponse)
  })
_sym_db.RegisterMessage(TouchDataResponse)

RmDataRequest = _reflection.GeneratedProtocolMessageType('RmDataRequest', (_message.Message,), {
  'DESCRIPTOR' : _RMDATAREQUEST,
  '__module__' : 'data_node_pb2'
  # @@protoc_insertion_point(class_scope:RmDataRequest)
  })
_sym_db.RegisterMessage(RmDataRequest)

WriteDataRequest = _reflection.GeneratedProtocolMessageType('WriteDataRequest', (_message.Message,), {
  'DESCRIPTOR' : _WRITEDATAREQUEST,
  '__module__' : 'data_node_pb2'
  # @@protoc_insertion_point(class_scope:WriteDataRequest)
  })
_sym_db.RegisterMessage(WriteDataRequest)

ReadDataRequest = _reflection.GeneratedProtocolMessageType('ReadDataRequest', (_message.Message,), {
  'DESCRIPTOR' : _READDATAREQUEST,
  '__module__' : 'data_node_pb2'
  # @@protoc_insertion_point(class_scope:ReadDataRequest)
  })
_sym_db.RegisterMessage(ReadDataRequest)

ReadDataResponse = _reflection.GeneratedProtocolMessageType('ReadDataResponse', (_message.Message,), {
  'DESCRIPTOR' : _READDATARESPONSE,
  '__module__' : 'data_node_pb2'
  # @@protoc_insertion_point(class_scope:ReadDataResponse)
  })
_sym_db.RegisterMessage(ReadDataResponse)



_DATANODE = _descriptor.ServiceDescriptor(
  name='DataNode',
  full_name='DataNode',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=236,
  serialized_end=407,
  methods=[
  _descriptor.MethodDescriptor(
    name='touch',
    full_name='DataNode.touch',
    index=0,
    containing_service=None,
    input_type=_EMPTYMSG,
    output_type=_TOUCHDATARESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='rm',
    full_name='DataNode.rm',
    index=1,
    containing_service=None,
    input_type=_RMDATAREQUEST,
    output_type=_EMPTYMSG,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='write',
    full_name='DataNode.write',
    index=2,
    containing_service=None,
    input_type=_WRITEDATAREQUEST,
    output_type=_EMPTYMSG,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='read',
    full_name='DataNode.read',
    index=3,
    containing_service=None,
    input_type=_READDATAREQUEST,
    output_type=_READDATARESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_DATANODE)

DESCRIPTOR.services_by_name['DataNode'] = _DATANODE

# @@protoc_insertion_point(module_scope)
